import type { editor } from 'monaco-editor';

// Night Owl Dark - based on Sarah Drasner's Night Owl theme
export const nightOwlDark: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'd6deeb', background: '011627' },
    { token: 'comment', foreground: '637777', fontStyle: 'italic' },
    { token: 'string', foreground: 'addb67' },
    { token: 'string.quoted', foreground: 'addb67' },
    { token: 'constant.numeric', foreground: 'f78c6c' },
    { token: 'constant.language', foreground: '82aaff' },
    { token: 'constant.language.boolean', foreground: 'ff5874' },
    { token: 'constant.language.null', foreground: 'ff5874' },
    { token: 'constant.language.undefined', foreground: 'ff5874' },
    { token: 'keyword', foreground: 'c792ea', fontStyle: 'italic' },
    { token: 'keyword.control', foreground: 'c792ea', fontStyle: 'italic' },
    { token: 'keyword.operator', foreground: '7fdbca' },
    { token: 'storage', foreground: 'c792ea', fontStyle: 'italic' },
    { token: 'storage.type', foreground: '82aaff' },
    { token: 'entity.name.function', foreground: '82aaff' },
    { token: 'entity.name.class', foreground: 'ffcb8b' },
    { token: 'entity.name.type', foreground: 'ffcb8b' },
    { token: 'entity.name.tag', foreground: '7fdbca' },
    { token: 'entity.other.attribute-name', foreground: 'addb67' },
    { token: 'support.function', foreground: '82aaff' },
    { token: 'support.type', foreground: 'addb67' },
    { token: 'support.class', foreground: 'ffcb8b' },
    { token: 'variable', foreground: 'addb67' },
    { token: 'variable.parameter', foreground: 'd7dbe0' },
    { token: 'variable.other', foreground: 'addb67' },
    { token: 'punctuation', foreground: 'd6deeb' },
    { token: 'punctuation.definition.tag', foreground: '7fdbca' },
    { token: 'meta.tag', foreground: '7fdbca' },
    { token: 'type', foreground: 'ffcb8b' },
    { token: 'type.identifier', foreground: 'ffcb8b' },
    { token: 'delimiter', foreground: 'd6deeb' },
    { token: 'delimiter.html', foreground: '7fdbca' },
    { token: 'tag', foreground: '7fdbca' },
    { token: 'attribute.name', foreground: 'addb67' },
    { token: 'attribute.value', foreground: 'addb67' },
    { token: 'number', foreground: 'f78c6c' },
    { token: 'regexp', foreground: '80cbc4' },
    { token: 'annotation', foreground: 'c792ea' },
    { token: 'invalid', foreground: 'ff5874' },
  ],
  colors: {
    'editor.foreground': '#d6deeb',
    'editor.background': '#011627',
    'editor.selectionBackground': '#5f7e9779',
    'editor.selectionHighlightBackground': '#5f7e9750',
    'editor.lineHighlightBackground': '#010E17',
    'editor.lineHighlightBorder': '#010E17',
    'editorCursor.foreground': '#80a4c2',
    'editorLineNumber.foreground': '#4b6479',
    'editorLineNumber.activeForeground': '#C5E4FD',
    'editorIndentGuide.background': '#5e81ce52',
    'editorIndentGuide.activeBackground': '#7e97ac60',
    'editorWhitespace.foreground': '#2e2040',
    'editorBracketMatch.background': '#5f7e9779',
    'editorBracketMatch.border': '#5f7e97',
    'editorGutter.background': '#011627',
    'diffEditor.insertedTextBackground': '#99b76d23',
    'diffEditor.insertedLineBackground': '#99b76d23',
    'diffEditor.removedTextBackground': '#ef535033',
    'diffEditor.removedLineBackground': '#ef535033',
    'scrollbar.shadow': '#010b14',
    'scrollbarSlider.background': '#5f7e9750',
    'scrollbarSlider.hoverBackground': '#5f7e9780',
    'scrollbarSlider.activeBackground': '#5f7e97a0',
  },
};

// Night Owl Light - ported from Sarah Drasner's Night Owl Light theme
export const nightOwlLight: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: '', foreground: '403f53', background: 'FBFBFB' },
    { token: 'comment', foreground: '989fb1', fontStyle: 'italic' },
    { token: 'string', foreground: 'c96765' },
    { token: 'string.quoted', foreground: 'c96765' },
    { token: 'constant.numeric', foreground: 'aa0982' },
    { token: 'constant.language', foreground: '4876d6' },
    { token: 'constant.language.boolean', foreground: 'bc5454' },
    { token: 'constant.language.null', foreground: 'bc5454' },
    { token: 'constant.language.undefined', foreground: 'bc5454' },
    { token: 'keyword', foreground: '994cc3', fontStyle: 'italic' },
    { token: 'keyword.control', foreground: '994cc3', fontStyle: 'italic' },
    { token: 'keyword.operator', foreground: '0c969b' },
    { token: 'storage', foreground: '994cc3', fontStyle: 'italic' },
    { token: 'storage.type', foreground: '994cc3' },
    { token: 'entity.name.function', foreground: '4876d6', fontStyle: 'italic' },
    { token: 'entity.name.class', foreground: '111111' },
    { token: 'entity.name.type', foreground: '111111' },
    { token: 'entity.name.tag', foreground: '994cc3' },
    { token: 'entity.other.attribute-name', foreground: '4876d6', fontStyle: 'italic' },
    { token: 'support.function', foreground: '4876d6' },
    { token: 'support.type', foreground: '4876d6' },
    { token: 'support.class', foreground: '111111' },
    { token: 'variable', foreground: '4876d6' },
    { token: 'variable.parameter', foreground: '403f53' },
    { token: 'variable.other', foreground: '4876d6' },
    { token: 'punctuation', foreground: '403f53' },
    { token: 'punctuation.definition.tag', foreground: '994cc3' },
    { token: 'meta.tag', foreground: '994cc3' },
    { token: 'type', foreground: '111111' },
    { token: 'type.identifier', foreground: '111111' },
    { token: 'delimiter', foreground: '403f53' },
    { token: 'delimiter.html', foreground: '994cc3' },
    { token: 'tag', foreground: '994cc3' },
    { token: 'attribute.name', foreground: '4876d6' },
    { token: 'attribute.value', foreground: 'c96765' },
    { token: 'number', foreground: 'aa0982' },
    { token: 'regexp', foreground: '0c969b' },
    { token: 'annotation', foreground: '994cc3' },
    { token: 'invalid', foreground: 'bc5454' },
  ],
  colors: {
    'editor.foreground': '#403f53',
    'editor.background': '#FBFBFB',
    'editor.selectionBackground': '#d3e8f8',
    'editor.selectionHighlightBackground': '#d3e8f880',
    'editor.lineHighlightBackground': '#F0F0F0',
    'editor.lineHighlightBorder': '#F0F0F0',
    'editorCursor.foreground': '#90A7B2',
    'editorLineNumber.foreground': '#90A7B2',
    'editorLineNumber.activeForeground': '#403f53',
    'editorIndentGuide.background': '#d9d9d9',
    'editorIndentGuide.activeBackground': '#bdbdbd',
    'editorWhitespace.foreground': '#d9d9d9',
    'editorBracketMatch.background': '#d3e8f8',
    'editorBracketMatch.border': '#93a1a1',
    'editorGutter.background': '#FBFBFB',
    'diffEditor.insertedTextBackground': '#49d0c522',
    'diffEditor.insertedLineBackground': '#49d0c522',
    'diffEditor.removedTextBackground': '#f76e6e22',
    'diffEditor.removedLineBackground': '#f76e6e22',
    'scrollbar.shadow': '#00000010',
    'scrollbarSlider.background': '#93a1a150',
    'scrollbarSlider.hoverBackground': '#93a1a180',
    'scrollbarSlider.activeBackground': '#93a1a1a0',
  },
};
